---
title: "Multiple VPs"
output: html_document
---

```{r}

library(SimSurvey)
library(plotly)
library(ggplot2)
library(tidyverse)
library(purrr)



set.seed(1)
seed_all <- sample(round(1:1000000),50, replace = F)

surveys_list = list()

for(i in 1:50) {
  set.seed(seed_all[i])
  surveys_list[[i]] <- sim_abundance(ages = 1:20, 
                           years = 1:20,
                           Z = sim_Z(log_mean = log(0.6), 
                                     log_sd = 0.1,
                                     phi_age = 0.9,
                                     phi_year = 0.6, 
                                     plot = FALSE),
                           R = sim_R(log_mean = log(3e+07), 
                                     log_sd = 0.5,
                                     random_walk = TRUE, 
                                     plot = FALSE),
                           N0 = sim_N0(N0 = "exp", 
                                       plot = FALSE), 
                           growth = sim_vonB(Linf = 100, 
                                             L0 = 5, 
                                             K = 0.2, 
                                             log_sd = 0.05, 
                                             plot = FALSE,
                                             length_group = 3))  %>%
  sim_distribution(grid = make_grid(x_range = c(-150, 150), 
                                    y_range = c(-150, 150),
                                    res = c(10, 10),
                                    shelf_depth = 200, 
                                    shelf_width = 50, 
                                    depth_range = c(10, 1000), 
                                    n_div = 1, 
                                    strat_breaks = seq(0, 1000, by = 40),
                                    strat_splits = 2, 
                                    method = "spline"), 
                   ays_covar = sim_ays_covar(range = 300, 
                                             phi_age = 0.8, 
                                             phi_year = 0.1),
                   depth_par = sim_parabola(mu = 200, sigma = 70, plot=FALSE)) %>%
  sim_survey(n_sims = 1,
  q = sim_logistic(k = 2, x0 = 3, plot = FALSE),
  binom_error = TRUE, 
  set_den = 2/1000) %>% 
  SimSurvey::run_strat()
  }
```


```{r}
xy <- NULL
xy[[1]] <- as_tibble(surveys_list[[i]]$grid_xy)
N[[i]] <- as_tibble(surveys_list[[i]]$setdet$N)
N[[i]]<- as_tibble(surveys_list[[i]]$setdet$n)
```
```{r}
data_survey <- as.data.frame(do.call(rbind, surveys_list))

tidy(surveys_list)


surveys_list %>%
     map_dbl(~summary(.x)$setdet) %>%
     data.frame(N = .) %>%
     ggplot( aes(x = N) ) +
          geom_density(fill = "blue", alpha = .5) 



```

