
# Abstract

Many data-limited stock assessments rely on survey indices for the provision of science advice. Estimates of stock size are often derived from design-based approaches, however, the quantification of uncertainty around these estimates remains a challenge. Standard practice has been to use quantiles from a Student's t distribution to approximate confidence intervals, however, this method sometimes produces negative values for positive quantities like biomass and abundance. As an alternate method, we propose the use of the Gamma distribution to approximate uncertainty around survey indices. This involves the translation of unbiased design-based mean and variance estimators to shape and scale parameters for the Gamma distribution. Via simulation testing, we show that densities and confidence intervals derived from the Gamma distribution closely match densities derived from bootstraped samples of simulated survey data. Results also indicate that the Gamma approximation offers a reasonable survey-based approach for quantifying the probability that a stock is above or below a reference level. Though these results are preliminary, they clearly demonstrate that the Gamma distribution offers a more realistic description of the uncertainty around survey indices than the Student's t distribution.

# Introduction

A primary objective of fisheries-independent trawl surveys is to obtain indices of stock size and quantify the uncertainty around these indices. Such information plays a critical role in the assessment and management of fish stocks around the world as they often serve as a leading indicator of trend and status [@pennington1998; @kimura2006]. Quantifying uncertainty around stock size, trends, and status is a challenging but necessary task as fisheries management increasingly relies on such information to characterize the risk associated with alternative management options. Whenever possible, this quantification of uncertainty is done using stock assessment models which are often calibrated using survey-based indices. However, data limitations, complex stock dynamics, and operational capacity constraints often preclude the implementation of complex stock assessment models. In these cases, the assessment of the stock tend to be based on the survey indices themselves, together with any additional biological and ecological information that may be available. Therefore, when assessments are survey-based, the quantification of uncertainty of the survey indices becomes a primary source for informing risk.

Fisheries surveys are generally based on standard sampling techniques and indices are commonly derived using design-based estimators. In the Northwest Atlantic, major bottom trawl surveys follow a stratified-random sampling design with proportional allocation [e.g., @gonzalez2022; @rideout2022], and the biomass and abundance indices are calculated accordingly [e.g., @smith1981]. The derivation of the standard mean and variance estimators from a stratified-random sampling design is constructed using the general properties of the mean and variance, building these estimators from the straightforward concept that the overall mean represents a weighted average of the strata means, and where the weights applied are constants derived from the stratification scheme [e.g., @cochran1977]. One important feature of this derivation is that it does not depend on any assumed distribution; the estimators of the mean and variance are valid irrespective of the underlying distribution. Approximate confidence intervals, in contrast, depend on an assumed distribution.

Standard confidence intervals are approximated using quantiles from a Normal distribution, when sample size is large, or a Student's t distribution, when sample sizes are small [i.e., few degrees of freedom per stratum\; @cochran1977]. However, given both distributions permit negative values, this standard assumption may not be reasonable when analyzing strictly positive quantities like biomass and abundance [@cadigan2011]. The issue of negative lower bounds from this approximation is therefore an artifact of the assumed distribution rather than the stratified-random mean and variance estimators. This justifies the application of resampling techniques like bootstrap to derive more realistic confidence intervals for stratified-random estimators.

While resampling techniques can be an effective tool to generate confidence intervals, depending on the case in hand, they could require additional computing power and programming efforts. These additional steps should not be a deterrent to implementing them when required but having a simpler alternative that addresses the issues linked to the normal approximation can also be useful. A cursory examination of biomass and abundance indices from research surveys not only shows that there are no negative values (naturally), but that the distributions are seldom symmetrical; long positive tails are often observed. Given these features, a logical choice for describing these data is the Gamma distribution. This distribution is always positive, and depending on the parametrization, it can be fairly symmetrical (i.e. normal-like) or have a long right tail. We propose that by simply changing the assumed distribution from Normal or Student's t to Gamma we can provide a better approximation to the confidence intervals which does not suffer from undesired features (e.g. negative lower values), while better resembling observed distributions (e.g. asymmetrical distribution with longer positive tails).

# Methods

## Calculating Gamma parameters

Provided data from a bottom trawl stratified-random survey, average biomass or abundance ($\hat{\mu}$) and sampling variance ($\hat{\sigma}^2$) over the stock area can be estimated using the standard random-stratified design calculations [@cochran1977; @smith1981; @smith1990]. These estimates can then be used to calculate the scale ($\hat{\theta}$) and shape ($\hat{\kappa}$) parameters of the corresponding Gamma distribution as:

\begin{equation}
  \hat{\theta} = \frac{\hat{\sigma}^2}{\hat{\mu}}, ~ \text{and} ~ \hat{\kappa} = \frac{\hat{\mu}^2}{\hat{\theta}}
  (\#eq:gamma)
\end{equation}

The resulting Gamma distribution is then assumed to describe the data and its quantiles are used to define the confidence intervals in the same way the Normal or Student's t distributions are used in the standard approach.

## Aggregating estimates

For some cases there might also be a need to calculate the probability that the current index is above or below an average level $\hat{\mu}_{r}$ from a reference period $R$. Since the reference point ${\hat{\mu}}_r$ is an average of the index itself, its value cannot be perfectly known and the uncertainty around it should also be taken into account in the estimation of the probability. Given that each individual index value included in the average has its own variance, a full consideration of the uncertainty around the average should also consider this variability. Therefore, to fully account for the uncertainty around ${\hat{\mu}}_r$ we need to combine the variances across the individual indices. This combined variance ${\hat{\sigma}}_r^2$ can be obtained by simply applying the general properties of the variance. Since ${\hat{\mu}}_r$ is effectively a linear combination of the individual indices (i.e., the sum of random variables multiplied by a constant - the inverse of sample size) the properties of the variance for a linear combination provides a way for estimating ${\hat{\sigma}}_r^2$. Furthermore, if we assume that the survey variances across years are independent, we can dismiss the covariances between years and ${\hat{\mu}}_r$ and ${\hat{\sigma}}_r^2$ can be estimated as:

\begin{equation}
  \hat{\mu}_{r} = \frac{\sum_{y = 1}^{|R|} \hat{\mu_y}}{|R|}, ~ \text{and} ~ \hat{\sigma}_r^2 = \frac{\sum_{y = 1}^{|R|} \hat{\sigma}^2_y}{|R|^2}
  (\#eq:mean)
\end{equation}

where $\hat{\mu_y}$ and ${\hat{\sigma}}_y^2$ are the estimated annual mean and variance for the index in each year $y$ within the reference period $R$, and where $\left|R\right|$ is the size of the period (i.e. the number of years used to compute the average). As above, ${\hat{\mu}}_r$ and ${\hat{\sigma}}_r^2$ can be converted to $\hat{\theta}$ and $\hat{\kappa}$ parameters to characterize the uncertainty assuming a Gamma distribution (Equation \@ref(eq:gamma)).

## Simulation testing

While the proposed approach only involves a change in the assumption made about the distribution of the estimated mean, establishing if it is more realistic than the customary Normal/Student's t distribution assumption requires additional analysis. To address this issue, we use simulations to test the performance of our proposed approach under two use cases: 1) the calculation of confidence intervals from a single survey index, and 2) the estimation of the probability the stock to be above or below some reference point.

We explored these two use cases by simulating a redfish-like population using the R package SimSurvey [@regular2020]. The simulated population was based on the exponential decay cohort model where parameter settings for mortality, recruitment, and growth were based on assessments of redfish in 3O and 3LN. The simulated population was distributed through an area according to the age-year-space covariance with a parabolic relationship with depth. This survey area was 300 x 300 km with 10 km^2^ cell size and had 30 depth-based strata. We simulated stratified random sampling with a 2 m wide trawl hauled for a distance of 1.5 km. The population and survey were simulated over 20 years. The number of sets in a stratum was proportional to its area (approximately 1 set per 1000 km^2^) and the minimum set per stratum was 2. The survey simulation was replicated five times over the same population.

To assess performance under use case 1, average trawlable abundance ($\hat{\mu}$) and sampling variance ($\hat{\sigma}^2$) was calculated by year (1-20) and replicate (1-5) using standard design-based estimators [@smith1981; @smith1990] and these estimates were translated to scale ($\hat{\theta}$) and shape ($\hat{\kappa}$) parameters for the Gamma distribution as described above (Equation \@ref(eq:gamma)). To compare probability densities obtained from the Gamma distribution with densities based on an empirical approach, we applied a non-parametric bootstrap to resample the observations (sets) independently within each stratum with replacement. The resampling and calculation of the mean bootstrap estimator were repeated 5000 times with the R package boot [@canty2021]. Densities from these boostrap samples were computed for each year and survey replicate for comparison to the Gamma approximation. Finally, standard confidence intervals were computed using the t-distribution for comparison to the bootstrap and Gamma approximations.

To assess performance under use case 2, estimates from years 10-15 were treated as the reference period and the average abundance and the associated variance was constructed by aggregating the annual estimates as described above (Equation \@ref(eq:mean)). These aggregate estimates were used to calculate the corresponding Gamma distribution parameters (Equation \@ref(eq:gamma)) to characterize the average abundance distribution for the reference period. Likewise, average stratified-estimate of abundance across years 10-15 were bootstraped to obtain samples for comparison with density from the Gamma approach. Using distributions derived from the Gamma distribution and bootstrap samples, the probability the population estimate from year 20 is lower than the reference period was computed for comparison.

This simulation can be replicated using code in [Appendix A](#app:appendix-a).

# Results and Discussion

Despite high variability in central tendency as a consequence of population variability and sampling noise, the shape of both the Gamma density and the bootstrap samples were similar across all years and survey replicates (Figure \@ref(fig:comp-den)). This result indicates that the Gamma distribution provides a reasonable approximation of the uncertainty around the stratified estimates. A comparison of the confidence intervals derived from the Gamma distribution relative to those obtained from bootstraping (Figure \@ref(fig:comp-ci)) further support this conclusion. Though 95% intervals from the Gamma distribution appear to be slightly tighter than those from the bootstrap method, our proposed approach clearly outperforms intervals approximated using the Student's t distribution (Figure \@ref(fig:comp-ci)). Finally, the Gamma intervals avoid unrealistic negative values.

The Gamma approximation also appears to have comparable performance to a bootstrap approach when assessing the probability the terminal estimate is below average levels from a reference period (Figure \@ref(fig:ref-den)). Across all five survey replicates, the mean relative difference between the probabilities computed using the two methods was < 0.04. Though preliminary and based on only five replicates, this result indicates the gamma approximation may offer a reasonable option for quantifying the uncertainty around stock status.

Taken together, these preliminary results indicate that the Gamma distribution offers a more realistic description of the uncertainty around survey indices of abundance than the Student's t distribution. It remains unclear, however, whether the performance of the Gamma approach is truly comparable to the bootstrap approach. Indeed, there is no consensus on how to apply bootstrapping in a stratified-random survey context [@cadigan2011], so the bootstrap results presented here may be biased. Further testing is therefore required where the true underlying population size across thousands of simulations is used to formally assess the coverage of the 95% confidence intervals.





