
\pagebreak

# Figures

```{r comp-den, fig.width = 7.5, fig.height = 8, fig.cap = "The bootstrap and gamma distributions estimated using simulated data from five independent surveys conducted over the same population across 20 years. The red area shows the density distribution from 1000 bootstrapped samples from each year and survey replicate. The blue area shows the gamma probability distribution from each year and survey replicate based on the mean and standard deviation of the design-based index."}
readRDS(here("Gamma_SCR/data/den_plot.rds"))
```

\pagebreak

```{r ref-den, fig.width = .nafo_width, fig.height = .nafo_height * 2, fig.cap = "Bootstrap (blue) and gamma (red) distributions estimated from simulation 1 of a redfish-like population, where terminal estimates (year 20; open area) are compared to a reference period (aggregate estimates from years 2-9; shaded area). Densities for the reference period were obtained by combining the bootstrap samples and by aggregate parameters across the reference period (see Methods section). Probability that the terminal value is below the reference point is indicated."}
load(here("Gamma_SCR/data/ref_plot.rda"))
ref_plot
```

\pagebreak


```{r red, fig.width = .nafo_width, fig.height = .nafo_height * 2, fig.cap = "Combined CAN-Spring and CAN-Autumn biomass index (top; blue line) with 80% confidence intervals (blue shaded area) calculated using a Gamma distribution. Horizontal line (red) indicates interim Blim = 0.3 Bmsy-proxy with 80% confidence intervals (red dashed lines). Probability of By < Blim is presented below."}
load(here("Gamma_SCR/data/red_plot.rda"))
red_plot
```

