---
title: "Approximating uncertainty around indices from stratified-random trawl surveys using the Gamma distribution"
author: "Paul M. Regular, Mariano Koen-Alonso, Semra Yalcin, Andrea M.J. Perreault, Laura J. Wheeland"
date: | 
    Northwest Atlantic Fisheries Center, Fisheries and Oceans Canada, P.O.Box 5667, St. John’s, NL, A1C 5X1, Canada\       
    \
    `r format(Sys.time(), "%Y-%m-%d")` 
output: NAFOdown::word_scr
knit: bookdown::render_book
link-citations: true
bibliography: bib/refs.bib
csl: csl/apa-no-ampersand.csl
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
# adjust as desired:
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = "knitr-figs-docx/",
  cache.path = "knitr-cache-docx/",
  fig.height = NAFOdown::.nafo_height,
  fig.width = NAFOdown::.nafo_width, 
  fig.showtext = TRUE,
  echo = FALSE,
  # autodep = TRUE,
  # cache = TRUE,
  cache.comments = FALSE,
  dev = "png",
  dpi = 600
)
showtext::showtext_opts(dpi = knitr::opts_chunk$get()$dpi) # force showtext dpi to match chunk dpi to preserve proper font size (9 pt)
```

```{r load-libraries, cache=FALSE}
# add other packages here:
library(NAFOdown)
library(ggplot2)
library(flextable)
library(here)
theme_set(theme_nafo()) # set default ggplot2 theme
```
